### ISSUE TITLE
Need Update VecNameCur, frnPfrnNameMap When Files created or deleted

### ISSUE THREAD

**Issue by zzk0** [LeiHao0/Fake-Everything#3]
The  VecNameCur, frnPfrnNameMap is built when the program start-up.

So, If someone deletes files when the program running, the search result will be not correct.

Is there any idea to update the list and the map?

**Comment by Artwalk** [comment]
hi, thanks for the issue, it's a demo project I wrote in university many years ago, you can folk and update it.

The intuition I can give is

1. set a timer, say, update every 5 minutes
2. register a handler about files change notifications
